name: SofaScraper to CSV

on:
  schedule:
    - cron: '*/20 * * * *' # Každých 20 minut
  workflow_dispatch: # Možnost ručního spuštění

# DŮLEŽITÉ: Povolení zápisu do repozitáře
permissions:
  contents: write

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Stáhnout kód repozitáře
        uses: actions/checkout@v3

      - name: Nastavit Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Nainstalovat knihovny
        run: pip install -r requirements.txt

      - name: Spustit skript (vytvoří results.csv)
        run: python main.py

      - name: Commit a Push změn
        run: |
          git config --global user.name "SofaBot"
          git config --global user.email "sofabot@users.noreply.github.com"
          git add results.csv
          # Commitneme jen pokud jsou změny, jinak nehlásíme chybu
          git commit -m "Aktualizace výsledků: $(date)" || exit 0
          git push
